# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160406_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_choice', models.IntegerField(null=True)),
                ('player2_choice', models.IntegerField(null=True)),
                ('player1_time', models.IntegerField(null=True)),
                ('player2_time', models.IntegerField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.GameSession')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Question')),
            ],
        ),
    ]
